# __license__   = 'GPL v3'
# __copyright__ = '2026, RelUnrelated <dan@relunrelated.com>'
from qt.core import (QDialog, QVBoxLayout, QHBoxLayout, QGridLayout, QLabel, QFrame, 
                     QLineEdit, QComboBox, QPushButton, QDialogButtonBox,
                     QTextEdit, QPixmap, Qt, QStyledItemDelegate, QPalette, QDoubleValidator,
                     QScrollArea, QWidget, QMessageBox)

from calibre_plugins.ai_vision_metadata.metadata_writer import MANUAL_FIELDS, validate_manual_fields

import typing
import re
from html import escape

# This block is only 'True' when PyCharm is reading the code.
# When Calibre runs the code, this is 'False' and gets completely ignored!
if typing.TYPE_CHECKING:
    def load_translations():
        pass
    def _(text: str) -> str:
        return text

try:
    load_translations()
except NameError:
    pass

_CALIBRE_TRANSLATE = _
_ZH_UI = {
    'Review AI Metadata': '审核 AI 元数据', 'Unknown Model': '未知模型', 'AI': 'AI',
    'Original filename': '原始文件名', 'Title': '标题', 'Creators': '作者', 'Series:': '丛书：', 'Index:': '序号：',
    'Tags': '标签', 'Languages': '语言', 'Publisher': '出版社', 'Published': '出版日期', 'Identifiers': '标识符', 'Comments': '备注',
    'Manual input only. AI suggestions are disabled; enter a value and check the box to write it.': '仅限手动输入。AI 建议已禁用；请输入值并勾选复选框后写入。',
    '(Julian Date)': '（儒略日期）', '(Week №)': '（周序号）', 'Invalid metadata': '元数据无效', 'Overwrite': '覆盖', 'Append': '追加',
    'Source: ': '来源：', '; Comments source: ': '；备注来源：', '; cover_image_supplied: false; cover preview is local only.': '；未发送封面；封面预览仅在本地显示。',
    "<center><b>{0} : {1}</b><br><span style='color: gray; font-size: 10px;'><i>(Processed in {2} seconds; confidence: {3})</i></span></center>": "<center><b>{0}：{1}</b><br><span style='color: gray; font-size: 10px;'><i>（耗时 {2} 秒；置信度：{3}）</i></span></center>",
    'yes': '是', 'no': '否', 'none': '无',
    'Original title': '原文标题', 'Circle': '社团', 'Translation group': '汉化组', 'Event': '展会', 'Edition': '版本', 'Title source': '标题来源',
    'AI source title: ': 'AI 识别的原文标题：', 'AI source authors: ': 'AI 识别的作者：', 'Chapter': '章节', 'Volume range': '卷号范围', 'Chapter range': '章节范围', 'Source title language: ': '原文语言：',
    '<i><b>Note:</b> The metadata above was generated by an AI model and may contain errors or inaccuracies. Please review each field carefully. Use the dropdowns to control whether data is overwritten or merged.</i>': '<i><b>提示：</b>以上元数据由 AI 模型生成，可能存在错误。请仔细审核每个字段，并使用下拉框选择覆盖或合并数据。</i>',
    '(Overwrite)': '（覆盖）', '(Read only)': '（只读）',
    'Existing metadata is shown for editing. Uncheck a field to leave it unchanged.': '已显示现有元数据供编辑；取消勾选即可保持该字段不变。',
}

_LANGUAGE_NAMES = {
    'zho': '中文', 'chi': '中文', 'jpn': '日语', 'ja': '日语', 'eng': '英语', 'en': '英语',
    'kor': '韩语', 'ko': '韩语', 'fra': '法语', 'fre': '法语', 'deu': '德语', 'ger': '德语',
    'spa': '西班牙语', 'ita': '意大利语', 'rus': '俄语', 'por': '葡萄牙语', 'ara': '阿拉伯语',
    'hin': '印地语', 'vie': '越南语', 'tha': '泰语', 'ind': '印度尼西亚语', 'nld': '荷兰语',
    'pol': '波兰语', 'tur': '土耳其语', 'ukr': '乌克兰语', 'heb': '希伯来语', 'lat': '拉丁语',
}
_COMMON_LANGUAGES = [('中文', 'zho'), ('日语', 'jpn'), ('英语', 'eng'), ('韩语', 'kor'),
                     ('法语', 'fra'), ('德语', 'deu'), ('西班牙语', 'spa'), ('俄语', 'rus'),
                     ('葡萄牙语', 'por'), ('阿拉伯语', 'ara')]

def _next_language_code(value):
    normalized = str(value).strip()
    if not normalized:
        return ''
    folded = normalized.casefold()
    for code, name in _LANGUAGE_NAMES.items():
        if folded == name.casefold():
            return 'zho' if code == 'chi' else ('jpn' if code == 'ja' else ('eng' if code == 'en' else code))
    return normalized

def _canonical_authors(value):
    parts = [part.strip() for part in re.split(r'\s*(?:&|,|，|、)\s*', str(value or '')) if part.strip()]
    return ' & '.join(parts)
def _(text: str) -> str:
    return _ZH_UI.get(text, _CALIBRE_TRANSLATE(text))

def _display_text(text: str) -> str:
    """Translate diagnostics that originate in schema validation rather than Qt strings."""
    replacements = {
        'Japanese source title was not translated into Chinese; automatic writing is skipped.': '日文原文未翻译为中文，已跳过自动写入。',
        'An AI translation still contained Japanese kana and was rejected.': 'AI 译文仍含日文假名，已拒绝该译文。',
        '#original_filename is empty or unavailable. The displayed source is a calibre directory, not the original filename.': '#original_filename 为空或不可用；当前来源是 calibre 目录名，不是原始文件名。',
        'Comments preserves the complete title text captured before this analysis. The original filename cannot be verified without #original_filename.': '备注保留了分析前捕获的完整标题；没有 #original_filename 无法验证原始文件名。',
        'Title evidence was recovered from the current title. Confirm the cleaned title and any AI translation before writing.': '标题依据来自当前标题；写入前请确认清理后的标题和 AI 译文。',
        'The AI could not confidently distinguish filename roles; automatic writing is skipped.': 'AI 无法可靠区分文件名字段，已跳过自动写入。',
        'Title identification is confident, but other roles are uncertain; only title and filename Comments are eligible for automatic writing.': '标题识别可靠，但其他字段不确定；自动模式只写入标题和文件名备注。',
        'Title evidence was recovered from plugin history because #original_filename is unavailable; verify the historical input if needed.': '由于 #original_filename 不可用，标题依据来自插件历史记录；如有需要请核对历史输入。',
        'Comments preserves input text recovered from plugin history; the original filename column is unavailable.': '备注保留了从插件历史记录恢复的输入文本；原始文件名列不可用。',
        'AI could not confidently distinguish filename roles; automatic writing is skipped.': 'AI 无法可靠区分文件名字段，已跳过自动写入。',
    }
    if text in replacements:
        return replacements[text]
    if text.startswith('AI filename roles rejected: '):
        return 'AI 文件名字段校验拒绝：' + text.split(': ', 1)[1]
    if text.startswith('Removed AI numbering without work-title evidence: '):
        return '已移除缺少作品标题依据的 AI 编号：' + text.split(': ', 1)[1]
    if text.startswith('Translation correction failed: '):
        return '译文校正失败：' + text.split(': ', 1)[1]
    return text

class DropdownDescriptionDelegate(QStyledItemDelegate):
    def paint(self, painter, option, index):
        # 1. Let Qt draw the standard item (handles the blue selection background and the main text)
        super().paint(painter, option, index)

        # 2. Check if we secretly attached a description to this item using the UserRole
        description = index.data(Qt.ItemDataRole.UserRole)
        if description:
            painter.save()
            
            # Use the system's muted placeholder color (usually a nice gray)
            color = option.palette.color(QPalette.ColorRole.PlaceholderText)
            painter.setPen(color)

            # Draw the description right-aligned with a 5px margin so it doesn't hug the scrollbar
            rect = option.rect
            rect.adjust(0, 0, -5, 0)
            painter.drawText(rect, Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter, description)
            
            painter.restore()

class EditableMetadataComboBox(QComboBox):
    """Editable combo with the small QLineEdit-compatible API used by the form."""
    def text(self):
        return self.currentText()

    def setText(self, value):
        self.setCurrentText(str(value))

class MetadataReviewDialog(QDialog):
    def __init__(self, parent, metadata, cover_path):
        super().__init__(parent)
        self.setWindowTitle(_("Review AI Metadata"))
        self.setMinimumWidth(900)
        
        self.layout = QVBoxLayout(self)
        self.metadata = metadata
        self.results = {}
        self.title_only = False
        
        # --- Centered Model Header ---
        model_name = metadata.get('ai_model_used', _('Unknown Model'))
        provider_name = metadata.get('ai_provider', _('AI'))
        duration = metadata.get('api_duration', 0.0)
        confidence = metadata.get('confidence')
        # Keep the header compact; detailed evidence remains available in run history.
        header_text = _(
            "<center><b>{0} : {1}</b><br>"
            "<span style='color: gray; font-size: 10px;'><i>(Processed in {2} seconds; confidence: {3})</i></span></center>"
        ).format(escape(str(provider_name)), escape(str(model_name)), duration, confidence if confidence is not None else "?")
        
        self.header_label = QLabel(header_text)
        self.header_label.setWordWrap(True)
        self.layout.addWidget(self.header_label)
        self.line = QFrame()
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.layout.addWidget(self.line)
        # ----------------------------------
        
        # --- Side-by-Side Layout Container ---
        self.middle_layout = QHBoxLayout()
        
        # 1. Left Side: The Cover Image
        self.cover_label = QLabel()
        if cover_path:
            import os
            if os.path.exists(cover_path):
                pixmap = QPixmap(cover_path)
                if not pixmap.isNull():
                    # Scale the image height to match the form, keeping it looking sharp
                    scaled_pixmap = pixmap.scaledToHeight(450, Qt.TransformationMode.SmoothTransformation)
                    self.cover_label.setPixmap(scaled_pixmap)
        
        # Pin the image to the top left so it doesn't float weirdly
        self.cover_label.setAlignment(Qt.AlignmentFlag.AlignTop | Qt.AlignmentFlag.AlignHCenter)
        self.middle_layout.addWidget(self.cover_label)
        
        # 2. Right Side: The Form
        self.form_layout = QVBoxLayout()
        self.row_counter = 0
        
        # --- HELPER FUNCTIONS (Zebra Striped Rows) ---
        def create_row_container():
            row_frame = QFrame()
            row_frame.setObjectName("formRow")
            if self.row_counter % 2 != 0:
                row_frame.setStyleSheet("QFrame#formRow { background-color: rgba(128, 128, 128, 64); border-radius: 4px; }")
            self.row_counter += 1
            
            row_layout = QHBoxLayout(row_frame)
            row_layout.setContentsMargins(5, 5, 5, 5)
            return row_frame, row_layout

        def add_field(key, label_text, value, allow_append=False, default_to_append=False, show_mode=True):
            if self.title_only and key != 'title':
                return
            row_frame, row_layout = create_row_container()

            # 1. The main label
            label = QLabel(f"<b>{label_text}</b>")
            label.setFixedWidth(110)
            label.setWordWrap(True)
            row_layout.addWidget(label)

            # 2. The dynamic action dropdown or static label
            action_combo = None
            if allow_append:
                action_combo = QComboBox()
                action_combo.addItems([_("Overwrite"), _("Append")])
                if default_to_append:
                    action_combo.setCurrentText(_("Append"))
                action_combo.setFixedWidth(90)
                row_layout.addWidget(action_combo)
            elif show_mode:
                static_label = QLabel("<span style='color: gray; font-size: 10px;'><i>" + _('(Overwrite)') + "</i></span>")
                static_label.setFixedWidth(90)
                row_layout.addWidget(static_label)
            else:
                spacer = QLabel()
                spacer.setFixedWidth(90)
                row_layout.addWidget(spacer)

            # 3. Calibre-style editable selectors for tags and languages.
            if key in ('tags', 'languages'):
                edit = EditableMetadataComboBox()
                edit.setEditable(True)
                edit.setInsertPolicy(QComboBox.InsertPolicy.NoInsert)
                options_key = 'tag_options' if key == 'tags' else 'language_options'
                options = list(metadata.get(options_key, []) or [])
                current = str(value) if value else ''
                if key == 'languages':
                    language_items = list(_COMMON_LANGUAGES)
                    for option in options:
                        code = str(option).strip()
                        item = (_LANGUAGE_NAMES.get(code, code), code)
                        if item not in language_items:
                            language_items.append(item)
                    for display, code in language_items:
                        edit.addItem(display, code)
                    current_codes = [x.strip() for x in current.split(',') if x.strip()]
                    current_display = ', '.join(_LANGUAGE_NAMES.get(code, code) for code in current_codes)
                    if current_display:
                        edit.setCurrentText(current_display)
                    else:
                        edit.setCurrentIndex(-1)
                        edit.setEditText('')
                else:
                    if current and current not in options:
                        options.insert(0, current)
                    edit.addItems(options)
                    if current:
                        edit.setCurrentText(current)
                    else:
                        # QComboBox selects the first library tag when the
                        # editable text is set to an empty string. Keep an
                        # empty tag field visibly empty instead.
                        edit.setCurrentIndex(-1)
                        edit.setEditText('')
                edit.setMinimumWidth(180)
            else:
                edit = QLineEdit(str(value) if value else "")
            row_layout.addWidget(edit, 1)

            self.form_layout.addWidget(row_frame)
            self.results[key] = {'widget': edit, 'action_combo': action_combo}

        def add_indented_combo_field(key, label_text, options, allow_append=False, default_to_append=False):
            if self.title_only:
                return
            row_frame, row_layout = create_row_container()

            # 1. Spacer to align the action column properly
            spacer = QLabel()
            spacer.setFixedWidth(110)
            row_layout.addWidget(spacer)

            # 2. The dynamic action dropdown or static label
            action_combo = None
            if allow_append:
                action_combo = QComboBox()
                action_combo.addItems([_("Overwrite"), _("Append")])
                if default_to_append:
                    action_combo.setCurrentText(_("Append"))
                action_combo.setFixedWidth(90)
                row_layout.addWidget(action_combo)
            else:
                static_label = QLabel("<span style='color: gray; font-size: 10px;'><i>" + _('(Overwrite)') + "</i></span>")
                static_label.setFixedWidth(90)
                row_layout.addWidget(static_label)

            # 3. Indented label
            label = QLabel(f"<b>{label_text}</b>")
            row_layout.addWidget(label)

            # 4. Combo input
            combo = QComboBox()
            combo.setEditable(True)
            combo.setMinimumWidth(150)

            if key == 'series_index':
                validator = QDoubleValidator(0.0, 999999.0, 2, combo)
                validator.setNotation(QDoubleValidator.Notation.StandardNotation)
                combo.setValidator(validator)

            combo.setItemDelegate(DropdownDescriptionDelegate(combo))

            unique_opts = []
            for opt in options:
                val = opt[0] if isinstance(opt, tuple) else opt
                desc = opt[1] if isinstance(opt, tuple) else ""

                if val and val not in unique_opts:
                    unique_opts.append(val)
                    combo.addItem(val)

                    if desc:
                        combo.setItemData(combo.count() - 1, desc, Qt.ItemDataRole.UserRole)

            row_layout.addWidget(combo, 1)  # Added stretch factor

            self.form_layout.addWidget(row_frame)
            self.results[key] = {'widget': combo, 'action_combo': action_combo}

        def add_text_area(key, label_text, value, allow_append=False, default_to_append=False):
            if self.title_only and key != 'original_filename':
                return
            row_frame, row_layout = create_row_container()

            # 1. The main label
            label = QLabel(f"<b>{label_text}</b>")
            label.setFixedWidth(110)
            label.setWordWrap(True)
            row_layout.addWidget(label, alignment=Qt.AlignmentFlag.AlignTop)

            # 2. The dynamic action dropdown or static label
            action_combo = None
            if allow_append:
                action_combo = QComboBox()
                action_combo.addItems([_("Overwrite"), _("Append")])
                if default_to_append:
                    action_combo.setCurrentText(_("Append"))
                action_combo.setFixedWidth(90)
                row_layout.addWidget(action_combo, alignment=Qt.AlignmentFlag.AlignTop)
            else:
                mode_label = _("(Read only)") if key == 'original_filename' else _("(Overwrite)")
                static_label = QLabel("<span style='color: gray; font-size: 10px;'><i>" + mode_label + "</i></span>")
                static_label.setFixedWidth(90)
                row_layout.addWidget(static_label, alignment=Qt.AlignmentFlag.AlignTop)

            # 3. Text area
            edit = QTextEdit()
            edit.setPlainText(str(value) if value else "")
            edit.setMaximumHeight(80)
            row_layout.addWidget(edit, 1)

            self.form_layout.addWidget(row_frame)
            self.results[key] = {'widget': edit, 'action_combo': action_combo}

        # --- BUILD THE FORM ---
        add_field("title", _("Title"), metadata.get('title', ''), allow_append=False, show_mode=False)

        details = []
        for key, label in [('original_title', 'Original title'), ('circle', 'Circle'),
                           ('translation_group', 'Translation group'), ('event_code', 'Event'),
                           ('edition', 'Edition'), ('title_source', 'Title source'),
                           ('chapter', 'Chapter'), ('volume_range', 'Volume range'),
                           ('chapter_range', 'Chapter range')]:
            if metadata.get(key):
                details.append(_(label) + '：' + str(metadata[key]))
        if metadata.get('title_language_hint'):
            language_hint = str(metadata['title_language_hint'])
            details.append(_('Source title language: ') + _LANGUAGE_NAMES.get(language_hint, language_hint))
        if metadata.get('filename_role_status') == 'accepted':
            roles = metadata.get('filename_roles', {})
            details.append(_('AI source title: ') + str(roles.get('title_text', '')))
            details.append(_('AI source authors: ') + ', '.join(roles.get('author_texts', [])))
        self.filename_details = QLabel('\n'.join(details))
        self.filename_details.setTextFormat(Qt.TextFormat.PlainText)
        self.filename_details.setWordWrap(True)
        self.form_layout.addWidget(self.filename_details)

        raw_creators = metadata.get('creators')
        if not raw_creators:
            rogue_editor = metadata.get('editor')
            rogue_author = metadata.get('author')
            if rogue_editor:
                raw_creators = [rogue_editor]
            elif rogue_author:
                raw_creators = [rogue_author]
            else:
                raw_creators = []

        creators_str = " & ".join(str(author).strip() for author in raw_creators if str(author).strip()) if isinstance(raw_creators, list) else _canonical_authors(raw_creators)
        add_field("authors", _("Creators"), creators_str, allow_append=True, default_to_append=False)

        series_val = str(metadata.get('series', '')).strip()
        vol = str(metadata.get('volume', '')).strip()
        iss = str(metadata.get('issue_number', '')).strip()

        index_options = []
        if vol and iss and vol.isdigit() and iss.isdigit():
            index_options.append((f"{vol}.{iss.zfill(2)}", ""))

        if iss: index_options.append((iss, ""))
        if vol: index_options.append((vol, ""))
        if metadata.get('day_of_year'):
            index_options.append((str(metadata.get('day_of_year')), _("(Julian Date)")))
        if metadata.get('week_of_year'):
            index_options.append((str(metadata.get('week_of_year')), _("(Week №)")))

        filtered_index_options = []
        for opt in index_options:
            val = opt[0]
            try:
                float(val)
                if '.' in val:
                    if len(val.split('.')[-1]) <= 2:
                        filtered_index_options.append(opt)
                else:
                    filtered_index_options.append(opt)
            except ValueError:
                pass

        add_field('series', _('Series:'), series_val, allow_append=False, show_mode=False)
        add_field('series_index', _('Index:'), (filtered_index_options[0][0] if filtered_index_options else ''), allow_append=False, show_mode=False)

        tags_str = ", ".join(metadata.get('tags', [])) if isinstance(metadata.get('tags', []), list) else str(
            metadata.get('tags', ''))
        add_field("tags", _("Tags"), tags_str, allow_append=True, default_to_append=True)

        langs_str = ", ".join(metadata.get('languages', ['eng'])) if isinstance(metadata.get('languages', ['eng']),
                                                                                list) else str(
            metadata.get('languages', 'eng'))
        add_field("languages", _("Languages"), langs_str, allow_append=True, default_to_append=False)

        add_field("publisher", _("Publisher"), metadata.get('publisher', ''), allow_append=False, show_mode=False)

        year_raw = metadata.get('pub_year')
        if year_raw and str(year_raw).strip().isdigit() and int(str(year_raw).strip()) > 1:
            year = str(year_raw).strip()
            month_raw = metadata.get('pub_month')
            month = str(month_raw).strip().zfill(2) if month_raw and str(month_raw).strip().isdigit() else "01"
            day_raw = metadata.get('pub_day')
            day = str(day_raw).strip().zfill(2) if day_raw and str(day_raw).strip().isdigit() else "01"
            pub_date = f"{year}-{month}-{day}"
        else:
            pub_date = ""

        displayed_pubdate = metadata.get('existing_pubdate', pub_date)
        if str(displayed_pubdate or '').startswith(('0001-', '0101-')):
            displayed_pubdate = ''
        add_field("pubdate", _("Published"), displayed_pubdate, allow_append=False, show_mode=False)
        add_field("identifiers", _("Identifiers"), metadata.get('ids', ''), allow_append=True,
                  default_to_append=True)
        add_text_area("comments", _("Comments"), metadata.get('comments', ''), allow_append=True,
                      default_to_append=False)
        if metadata.get('existing_metadata_mode'):
            for key in ('tags', 'publisher', 'pubdate', 'identifiers'):
                widget = self.results[key]['widget']
                widget.setToolTip(_("Existing metadata is shown for editing; save the values currently displayed."))
        else:
            for key in ('tags', 'publisher', 'pubdate', 'identifiers'):
                widget = self.results[key]['widget']
                if isinstance(widget, QComboBox):
                    widget.setCurrentIndex(-1)
                    widget.setEditText('')
                else:
                    widget.clear()
                self.results[key]['widget'].setToolTip(_("Enter a value directly or choose one from the dropdown."))
        self.results['pubdate']['widget'].setPlaceholderText('YYYY-MM-DD')
        self.results['identifiers']['widget'].setPlaceholderText('isbn:123, custom:value')

        self.form_layout.addStretch(1)

        # Add the completed form to the right side of the middle layout
        form_widget = QWidget()
        form_widget.setLayout(self.form_layout)
        self.form_scroll = QScrollArea()
        self.form_scroll.setWidgetResizable(True)
        self.form_scroll.setWidget(form_widget)
        self.form_scroll.setMinimumHeight(450)
        self.middle_layout.addWidget(self.form_scroll, 1)
        self.layout.addLayout(self.middle_layout)

        # --- AI Disclaimer & Buttons ---
        disclaimer_text = _(
            "<i><b>Note:</b> The metadata above was generated by an AI model and may contain errors or inaccuracies. "
            "Please review each field carefully. Use the dropdowns to control whether data is overwritten or merged.</i>"
        )
        self.disclaimer_label = QLabel(disclaimer_text)
        self.disclaimer_label.setWordWrap(True)
        font = self.disclaimer_label.font()
        font.setPointSize(max(8, font.pointSize() - 1))
        self.disclaimer_label.setFont(font)
        self.disclaimer_label.setContentsMargins(0, 10, 0, 10)
        self.layout.addWidget(self.disclaimer_label)

        self.button_box = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel)
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)
        self.layout.addWidget(self.button_box)

    def accept(self):
        try:
            validate_manual_fields(self.get_approved_data())
        except ValueError as error:
            QMessageBox.warning(self, _("Invalid metadata"), str(error))
            return
        super().accept()

    def get_approved_data(self):
        approved = {}
        for key, data in self.results.items():
            widget = data['widget']
            action_combo = data.get('action_combo')

            if isinstance(widget, QComboBox):
                val = widget.currentText().strip()
                if key == 'languages':
                    selected_code = widget.currentData()
                    if selected_code:
                        val = str(selected_code)
                    else:
                        val = ', '.join(_next_language_code(part.strip()) for part in val.split(',') if part.strip())
            elif isinstance(widget, QTextEdit):
                val = widget.toPlainText().strip()
            else:
                val = widget.text().strip()

            if key == 'authors':
                val = _canonical_authors(val)

            action = "append" if action_combo and action_combo.currentIndex() == 1 else "overwrite"
            approved[key] = {'value': val, 'action': action}
            if key in MANUAL_FIELDS and val:
                approved[key]['manual'] = True

        return approved
